# Generated by Django 3.2.7 on 2024-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=False, help_text='Are you looking to Market a Property?', verbose_name='Agent'),
        ),
    ]
