FROM python:3.11.0-slim-buster

ENV APP_HOME =/APP_HOME
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/statistics
WORKDIR $APP_HOME

LABEL maintenance='api.imperfect@gmail.com'
LABEL youtube="value"
LABEL description="Development image for Real Estate Project"

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONNUNBUFFERED 1

RUN apt-get update \
&& apt-get install -y build_essential \
&& apt-get install -y libpq-dev \
&& apt-get install -y gettext \
&& apt-get install -y netcat gcc postgresql \
&& apt-get purge -y --autoremove -o APT::AutoRemove::RecommendsImportant=false \
&& rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip3

COPY ./requirements.txt /app/requirements.txt

RUN pip3 install -r requirements.txt

COPY ./docker/local/django/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./docker/local/django/start /start
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /start

COPY ./docker/local/django/celery/worker /start/start-celeryworker
RUN sed -i 's/\r$//g' /start-celeryworker
RUN chmod +x /start-celeryworker

COPY ./docker/local/django/celery/flower /start/start-flower
RUN sed -i 's/\r$//g' /start-flower
RUN chmod +x /start-flower



ENTRYPOINT [ "/entrypoint" ]