# Generated by Django 3.2.7 on 2024-02-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampUUIDModel',
            fields=[
                ('pkid', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
