# Generated by Django 3.2.7 on 2024-02-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStampUUIDModel',
        ),
    ]
